# Generated by Django 6.0.3 on 2026-03-14 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache_dir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.CharField(max_length=100)),
                ('start_txt', models.CharField(default='', max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('end_txt', models.CharField(default='', max_length=100)),
                ('predict_money', models.IntegerField()),
                ('context', models.CharField(max_length=1000)),
                ('max_people', models.IntegerField(default=4)),
                ('start_time', models.IntegerField(default=1773501750)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.rooms')),
            ],
        ),
    ]
